# ---------- Stage 1: Build ----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copy files
COPY . .

RUN npm install

RUN npm run build

# ---------- Stage 2: Serve ----------
FROM nginx:alpine AS production

ENV NODE_ENV=production

COPY --from=builder /app/dist/ /usr/share/nginx/html
COPY --from=builder /app/ngnix.config /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]